$ANSIBLE_VAULT;1.1;AES256
36383664643833643732313534663430383033613834323535383765386637646539643062653834
6366346232376333323039343633613039623236313332650a393039316433336339313433376263
39363863653464626665393266626461366136613837313632633437343361363332663831366233
3961346632616666610a356466363639383036383435316465366661373133333935643762353232
33373832643730333230623363353332363266623933353165313436346266346431383331353231
6432383433346630633566353830323236363366363433396339

