$ANSIBLE_VAULT;1.1;AES256
39383832353664333237353034376666656531646333633032363236346434643035643265306337
3934633336646230386333333638373034613730333634660a393738346435336261616131323736
63666531613065633330616237323930623030383666343766656263616538323163623230396163
3431376536613936360a366433623439383662653831656463643830623962333539636363343530
66393833613338323465303830396132643762373962626161366164336564353432616465353734
6562386365313036616637633736623938353063653536343862
