# - name: checking include-vs-import

#   ansible.builtin.import_role:
#   #ansible.builtin.include_role:
#    name: common
#    tasks_from: include-vs-import.yaml
#   when: os == "RedHat"

- name: checking include-vs-import

  ansible.builtin.include_role:
  #ansible.builtin.import_role:
   name: common
   tasks_from: include.yaml
  when: os == "RedHat"
  loop:
   - ram
   - cam