- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: present
  
- name: enable and start the mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup mysql authentication
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"