- name: app-setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup.yaml

- name: nodejs-setup
  ansible.builtin.import_role:
   name: common
   tasks_from: nodejs-setup.yaml

- name: systemd-setup
  ansible.builtin.import_role:
   name: common
   tasks_from: systemd-setup.yaml

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  
- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: check schema loaded or not
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: load mongodb master data
  ansible.builtin.shell: mongosh --host ""{{ MONGODB_HOST }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: enable and start the server
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes
