- name: copying {{ component }} systemd service
  ansible.builtin.template:
   src: "{{ component }}.service.j2"
   dest: "/etc/systemd/system/{{ component }}.service"
   remote_src: yes

- name: reload the daemon
  ansible.builtin.systemd_service:
      daemon_reload: true